### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by jbabijczuk** [SandroLuck/SonarDelphi#3]
I think that the "uses" block should never be marked as a duplicate.
It often happens that two units have the same this block and it is not a mistake.

![screen2](https://cloud.githubusercontent.com/assets/17296832/19054591/61f79962-89c0-11e6-8431-71b6fb1664e0.jpg)

**Comment by SandroLuck** [comment]
I see your point we somehow never realised this. I'm gonna think about a easier solution. But since this feature has its uses we'll keep it.
