### ISSUE TITLE
Sonarqube 6.2 Support

### ISSUE THREAD

**Issue by utricularia** [SandroLuck/SonarDelphi#6]
Hello Sandroluck,
I was wondering if you had any plans to update your fork of the project to support Sonarqube 6.2. We just set Sonarqube up and are trying to decide whether to downgrade to the LTS, or possibly fork the project and try to update it.

**Comment by utricularia** [comment]
I am new to the code base but if it would help, if you have some direction regarding what needs to happen to get the plugin updated- I may be able to lend some help.

**Comment by SandroLuck** [comment]
I'm sorry to disappoint you but no additional development is planned for the next months. I guess updating is not hard in general but it is hard to update without loosing tests and functionality (most of the code is deprecated in both java and sonarqube). If you want to start updating the plugin:
1) try getting the maven build running 
2) simply overwrite the entry in the pom.xml with the new sonar version (step by step is recommended)
3) deactivate all tests and libraries that use older java versions
4) Check which features still work and try fixing the ones that don't

Note: I finished this LTS version just befor the 6.0 upgrade it might be that it has become easier, but i guess the main problem is to get the plugin to run in 6.0 usually the upgrade from 6.xx to 6.xx will be easy (just change the entry in the pom.xml)

**Comment by utricularia** [comment]
Thank you for the suggestions. I forked your fork and am putting the updates in now.
